"""Durable ticket contracts and action ledger"""

import sqlalchemy as sa
from alembic import op

revision = "0002_tickets"
down_revision = "0001_runtime"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_catalogs",
        sa.Column("version", sa.String(length=200), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "ticket_workflows",
        sa.Column("workflow_id", sa.String(length=80), nullable=False),
        sa.Column("tenant_id", sa.String(length=200), nullable=False),
        sa.Column("ticket_id", sa.String(length=200), nullable=False),
        sa.Column("worker_role", sa.String(length=20), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("tracking", sa.JSON(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=True),
        sa.Column("latest_sequence", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("workflow_id"),
        sa.UniqueConstraint("tenant_id", "ticket_id", name="uq_ticket_owner"),
    )
    op.create_table(
        "ticket_actions",
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=80), nullable=False),
        sa.Column("authorized_sequence", sa.BigInteger(), nullable=False),
        sa.Column("terms_digest", sa.String(length=64), nullable=False),
        sa.Column("worker_role", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("data_kind", sa.String(length=20), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "state IN ('planned', 'in_flight', 'uncertain', 'verified', 'superseded', 'cancelled')",
            name="ticket_action_state",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["ticket_workflows.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    op.create_index(
        op.f("ix_ticket_actions_workflow_id"), "ticket_actions", ["workflow_id"], unique=False
    )
    op.create_table(
        "ticket_audit",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=80), nullable=False),
        sa.Column("event_key", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("reason_code", sa.String(length=200), nullable=False),
        sa.Column("metadata_refs", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["ticket_workflows.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        op.f("ix_ticket_audit_workflow_id"), "ticket_audit", ["workflow_id"], unique=False
    )
    op.create_table(
        "ticket_inbox",
        sa.Column("event_key", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=80), nullable=False),
        sa.Column("external_event_id", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=True),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result_tracking", sa.JSON(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('ticket', 'cancel')", name="ticket_event_kind"),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["ticket_workflows.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("event_key"),
        sa.UniqueConstraint("workflow_id", "external_event_id", name="uq_ticket_event"),
    )
    op.create_index(
        op.f("ix_ticket_inbox_workflow_id"), "ticket_inbox", ["workflow_id"], unique=False
    )
    op.create_table(
        "ticket_reminders",
        sa.Column("reminder_id", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=80), nullable=False),
        sa.Column("cycle_id", sa.String(length=64), nullable=False),
        sa.Column("recipient_ref", sa.String(length=200), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("missing_fields", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["ticket_workflows.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("reminder_id"),
        sa.UniqueConstraint(
            "workflow_id", "recipient_ref", "local_date", name="uq_daily_ticket_recipient"
        ),
    )
    op.create_index(
        op.f("ix_ticket_reminders_workflow_id"), "ticket_reminders", ["workflow_id"], unique=False
    )
    op.create_table(
        "fixture_effects",
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("fail_once_triggered", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["ticket_actions.action_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fixture_effects")
    op.drop_index(op.f("ix_ticket_reminders_workflow_id"), table_name="ticket_reminders")
    op.drop_table("ticket_reminders")
    op.drop_index(op.f("ix_ticket_inbox_workflow_id"), table_name="ticket_inbox")
    op.drop_table("ticket_inbox")
    op.drop_index(op.f("ix_ticket_audit_workflow_id"), table_name="ticket_audit")
    op.drop_table("ticket_audit")
    op.drop_index(op.f("ix_ticket_actions_workflow_id"), table_name="ticket_actions")
    op.drop_table("ticket_actions")
    op.drop_table("ticket_workflows")
    op.drop_table("ticket_catalogs")
    # ### end Alembic commands ###
